{{- if not .Values.postgresql.existingSecret }}
{{- $password := include "gpu-telemetry.password" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gpu-telemetry.fullname" . }}-db
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "gpu-telemetry.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgresql.username | quote }}
  password: {{ $password | quote }}
  database-url: {{ printf "postgres://%s:%s@%s-postgresql:5432/%s?sslmode=disable" .Values.postgresql.username $password (include "gpu-telemetry.fullname" .) .Values.postgresql.database | quote }}
{{- end }}
